### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by jacky68147527** [phosae/x-kubernetes#2]
请问可以实现该APIserver通过informer机制作为真实APIserver的只读服务吗

**Comment by phosae** [comment]
> 请问可以实现该APIserver通过informer机制作为真实APIserver的只读服务吗

没太看懂意思，可以展开讲讲吗

可以来个 [mermaid](https://mermaid.js.org/syntax/sequenceDiagram.html) 流程图

**Comment by jacky68147527** [comment]
感谢回复，场景是这样的：
目前我们碰到一个集群某些workload的pods非常多，查询时会造成APIServer压力很大，虽然我们已经加上resourceVesion=0，但还是会有卡顿的情况（k8s集群是云厂商托管的），因此我们想在中间加一层只读的APIServer，暂时命名为CustomAPIServer。
CustomAPIServer 通过informer机制与k8s集群进行数据同步，这样既可以支持client-go或kubectl查询k8s APIServer的请求，也降低了k8s APIServer的压力，CustomAPIServer也可以分摊很大的读压力，并且可以自定义的进行横向扩容。
大致的调用流程如下：
client-go/kubectl  -->  x-kubernetes --> k8s APIServer

辛苦大佬帮忙指导~

**Comment by phosae** [comment]
@jacky68147527 

写了一个基本可用的实现 https://github.com/phosae/x-kubernetes/pull/3

使用姿势啥的都写在 [README](https://github.com/phosae/x-kubernetes/blob/942c443e9a4e968f2c612ae9ac84fd89ad6c6bdd/apiserver-proxy/README.md)

可以看看一下

**Comment by yeahx** [comment]
有没有可能加一个简单的authz/authn功能？

**Comment by phosae** [comment]
> 有没有可能加一个简单的authz/authn功能？

具体是指？目前 
authn
- authn client-CA，验证客户端 x509 证书
- authn TokenReview，针对 serviceaccount token，会委托给 kube-apiserver 处理

authz
- SubjectAccessReview, 委托给 kube-apiserver 处理

**Comment by yeahx** [comment]
> 
先说下使用场景，因为种种原因无法在原集群上注册 CRD，所以自己实现了 APIServer，又不能通过 `SubjectAcessReview` 的方式来完成鉴权。

我的想法就是仿照 `DefaultBuildHandlerChain` 中认证授权部分的拦截器，比如 `WithAuthentication` 的部分，实现一个 Basic auth 就能完成的简单认证鉴权的拦截器（如果使用默认的 basic auth 或 sa的认证还得完成一部分 legcay api）

**Comment by phosae** [comment]
看起来是缺 authz 
在你们的 APIServer 里面实现一个 [ABAC](https://kubernetes.io/docs/reference/access-authn-authz/abac/) 是不是就行？
这样还是可以走 TokenReview 复用 kube-apiserver 的用户

**Comment by jacky68147527** [comment]
非常感谢，正在部署中……

**Comment by jacky68147527** [comment]
非常感谢@phosae大佬提供的解决方案，目前主体功能可以正常运行~

**Comment by phosae** [comment]
> 非常感谢@phosae大佬提供的解决方案，目前主体功能可以正常运行~

客气哈，我也有所收获
后续可以 PR 一起改进 👻
