### ISSUE TITLE
Could you please support HTTP ？

### ISSUE THREAD

**Issue by t-dijia** [phosae/x-kubernetes#4]
Could you please support HTTP when using Kubectl or a browser to access Apiserver proxy? HTTPS certificates can be quite troublesome

**Comment by phosae** [comment]
@t-dijia 
kube-apiserver insecure port is removed in v1.20, see [issues/91506](https://github.com/kubernetes/kubernetes/issues/91506).

It's reasonable to be consistent with the kube-apiserver.

apiserver-proxy is expose as NodePort Service listen on host port 30443. so you can connect to apiserver-proxy with kubectl like this

```
mv ~/.kube/{config,config.pxy}
sed -i 's~server: https://[^:]*:[0-9]*~server: https://172.18.0.2:30443~g' config.pxy
KUBECONFIG=~/.kube/config.pxy kubectl get po
```

for browser access, just expose plain HTTP using `KUBECONFIG=~/.kube/config.pxy kubectl proxy`

```mermaid
flowchart LR
c((.kube/config))
cc((.kube/config.pxy))

c --> |cp| cc
cc --> |chx apiserver<br/> addr|cc
kubectl --config--> kube-apiserver
kubectl --config.pxy--> apiserver-proxy
apiserver-proxy <--> kube-apiserver
```
